config/routes.rb
Rails.application.routes.draw do
  resources :players, only: [:new, :create]
  resources :games, only: [:new, :show] do
    resources :moves, only: [:create]
  end

  root 'players#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :player_x, class_name: 'Player'
  belongs_to :player_o, class_name: 'Player', optional: true
  has_many :moves, dependent: :destroy

  enum status: { waiting_for_player: 'waiting_for_player', in_progress: 'in_progress', finished: 'finished' }

  def current_turn_player
    current_turn == 'X' ? player_x : player_o
  end
end

app/models/move.rb
class Move < ApplicationRecord
  belongs_to :game
  belongs_to :player

  validates :position, inclusion: { in: 0..8 }
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @player = Player.find(params[:player_id])
    @game = Game.where(status: 'waiting_for_player').first

    if @game
      @game.update(player_o: @player, status: 'in_progress')
    else
      @game = Game.create(player_x: @player, current_turn: 'X', status: 'waiting_for_player')
    end

    redirect_to game_path(@game)
  end

  def create
    player_x = Player.find(params[:game][:player_x_id])
    @game = Game.create!(player_x: player_x, current_turn: 'X', status: 'waiting_for_player')
    redirect_to game_path(@game)
  end

  def show
    @game = Game.find(params[:id])
  end

  def join
    @game = Game.find(params[:id])
    player_o = Player.find(params[:player_o_id])
    if @game.status == 'waiting_for_player'
      @game.update!(player_o: player_o, status: 'in_progress')
    end
    render json: @game
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  protect_from_forgery with: :null_session

  def create
    @game = Game.find(params[:game_id])
    player = @game.current_turn_player
    position = params[:position].to_i

    game_service = GameService.new(@game)
    if game_service.make_move(player, position)
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace("game_board", partial: "games/board", locals: { game: @game }),
            turbo_stream.replace("game_status", partial: "games/status", locals: { game: @game })
          ]
        end
        format.html { redirect_to @game }
      end
    else
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace("error_message", partial: "shared/error", locals: { message: "Invalid move" }) }
        format.html { redirect_to @game, alert: "Invalid move" }
      end
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to new_game_path(player_id: @player.id)
    else
      render :new
    end
  end

  private

  def player_params
    params.require(:player).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/games/_board.html.erb
<p>Rendering board partial...</p>
<table border="1">
  <% (0..2).each do |row| %>
    <tr>
      <% (0..2).each do |col| %>
        <td data-action="click->game#makeMove" data-game-row-value="<%= row %>" data-game-col-value="<%= col %>">
          <% move = game.moves.find_by(position: row * 3 + col) %>
          <% if move %>
            <%= move.player == game.player_x ? 'X' : 'O' %>
          <% else %>
            &nbsp;
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/games/_status.html.erb
<p>Status: <%= @game.status %></p>

app/views/games/new.html.erb
<h1>Start a new game</h1>
<%= form_with(model: @game, local: true) do |form| %>
  <%= form.hidden_field :player_x_id, value: @game.player_x_id %>

  <div class="actions">
    <%= form.submit "Start Game" %>
  </div>
<% end %>

app/views/games/show.html.erb
<h1>Tic-Tac-Toe</h1>
<div id="game_status">
  <%= render partial: 'status', locals: { game: @game } %>
</div>
<div id="error_message"></div>
<div id="game_board" data-controller="game" data-game-id="<%= @game.id %>">
  <%= turbo_frame_tag "game_board" do %>
    <%= debug(@game.id) %>
    <%= render partial: 'board', locals: { game: @game } %>
    <p>Rendering board...</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicTacToe</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <%= yield %>
  <%= turbo_include_tags %>
</body>
</html>

app/views/players/create.html.erb
<h1>Players#create</h1>
<p>Find me in app/views/players/create.html.erb</p>

app/views/players/new.html.erb
<!-- app/views/players/new.html.erb -->
<h1>Enter your name to start the game</h1>
<%= form_with(model: @player, local: true, url: players_path) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit "Start Game" %>
  </div>
<% end %>

app/views/shared/_error.html.erb
<div id="error_message">
  <p><%= message %></p>
</div>